### ISSUE TITLE
[bug] la vue notifications ne charge pas les notifications

### ISSUE THREAD

**Issue by AugustinSeguin** [Eco-Gest/Frontend-Flutter#108]
" je pense que le souci se passe dans NotificationService.onEvent(). Je pense que le format de données n'est pas le bon entre ce qui est sur pusher (debug console) et ce qui est lu dans cette fonction."

**Comment by eleonoreeuzenes** [comment]
Flutter se co à pusher ✅
Flutter reçoi tbien les datas de l'API ✅
Problème au niveau du mapping de la réponse de l'API il semblerait..
