### ISSUE TITLE
[BUG] Rechargement de l'application pour pouvoir afficher les posts créés/image de profil modifiée

### ISSUE THREAD

**Issue by LaitAh** [Eco-Gest/Frontend-Flutter#19]
Pour plus de détail : 

- [PR 194 de O'Clock Méduse](https://github.com/O-clock-Meduse/projet-09-ecogest-front/pull/194)
- Fil "PR 194 upload" de #annonces-pr-mobile (Discord)

**Comment by AugustinSeguin** [comment]
J'ai analysé le bug mais c'est que ça prend du temps à se mettre à jour niveau backend... j'ai pas de solution pour le moment
